adds fitures for api
AlexUKDev/nodejs-contacts-rest-api pull request #1
Opened 2023-01-06 14:26 UTC by AlexUKDev

Здаэться все працює. Але коли у постмані оновлюєш підряд по одному і тому ж id (різні поля) здаэться помилка виникає і лягає апа. Не розумію в чому проблема. Буду взячний за кодрівʼю

2023-01-06 20:52 UTC, KhYulian commented on .vscode/settings.json
> +}
.vscode/ додайте в .gitignore та видаліть з репозиторію

2023-01-06 20:53 UTC, KhYulian commented on models/contacts.js
> +  }
console.log(error); - не надто корисно. try catch з цих функцій можете видалити. Помилки обробляти будете в контроллері

2023-01-06 20:54 UTC, KhYulian commented on routes/api/contacts.js
> +    console.log(error);
next(error)

2023-01-06 20:55 UTC, KhYulian commented on routes/api/contacts.js
> +  }
Для перевірки полів потрібно використовувати схеми Joi

2023-01-06 20:58 UTC, KhYulian commented
для створення та оновлення контакту маютть бути створені схеми Joi, де будуть зазначені поля, та якими вони мають бути. В контроллерах будете здійснювати валідацію joiSchema.validate(req.body) - для прикладу

2023-01-06 20:59 UTC, KhYulian commented
Відповідайте на коменти по мірі виправлення :)

2023-01-06 20:59 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-07 12:56 UTC, AlexUKDev commented on routes/api/contacts.js
> +  }
Я попередні виправив і не написав коменти. Так додав паку .vscode/ у .gitignore . Встановив Joi ознайомився із документацією трохи та здійснив конфігурацію валідації (майже дефолтні). Додав у  роути на метод POST (там всі поля обовʼязкові) та PUT ( всі поля не обовʼязкові, так як може оновлюватись одне значення властивості обʼєкту). Трохи погрався з обʼктом який вертає Joi, та массивом помилок. Кастомізував респорс помилки.

2023-01-07 14:04 UTC, KhYulian approved these changes
👌

2023-01-07 14:04 UTC, merged