Hw03 express
AlexUKDev/nodejs-contacts-rest-api pull request #2
Opened 2023-01-13 16:59 UTC by AlexUKDev

1. Adds db/connectionMongoDb.js (aads connection and configure it);
2. Adds model/contactModel.js (created  and configured contactSchema => compiled instance Contact)
3. Adds controllers/contactsController.js (logic moved here)
4. Updated Joi schema object  (addContactSchema and updateContactSchema adds favorite in rule)
5. Updated code of routes/api/contacts.js (now code is cleaner than it was)
6. Tested requests on  postman  (all responses are correct)
7.Adds new route (PATCH /api/contacts/:contactId/favorite)

2023-01-13 18:39 UTC, KhYulian commented
> 1. Adds db/connectionMongoDb.js (aads connection and configure it);
> 2. Adds model/contactModel.js (created  and configured contactSchema => compiled instance Contact)
> 3. Adds controllers/contactsController.js (logic moved here)
> 4. Updated Joi schema object  (addContactSchema and updateContactSchema adds favorite in rule)
> 5. Updated code of routes/api/contacts.js (now code is cleaner than it was)
> 6. Tested requests on  postman  (all responses are correct)
>    7.Adds new route (PATCH /api/contacts/:contactId/favorite)

*Added. 
5) Refactored routes/api/contacts.js
6) in Postman
7) Added a new endpoint for updating the contact's favorite field

2023-01-13 18:46 UTC, KhYulian requested changes
Структура в порядку :)

2023-01-13 18:46 UTC, KhYulian commented on controllers/contactsController.js
> +
немає потреби вручну шукати елемент і перевіряти чи він є. Якщо findByIdAndUpdate не знайде контакт, то нічого не оновить, можете вивчити відповідь у випадку, коли контакт не знайдено і відповідно обробити такий випадок

2023-01-13 18:46 UTC, KhYulian commented on controllers/contactsController.js
> +  }
Валідацію потрібно винести в окрему middleware, яка спрацьовуватиме перед контроллером

2023-01-13 18:46 UTC, KhYulian commented on controllers/contactsController.js
> +    }
Аналогічно

2023-01-13 18:46 UTC, KhYulian commented on db/connectionMongoDb.js
> +// const options = {};
?

2023-01-13 18:46 UTC, KhYulian commented on server.js
> +startServer();
Можна використати IIFE

2023-01-13 19:10 UTC, AlexUKDev commented on db/connectionMongoDb.js
> +// const options = {};
Що не так? якщо передавати обʼєктом свариться в консолі що такий спосіб застарів. Це я нагуглив. Так працює

2023-01-13 19:51 UTC, AlexUKDev commented on controllers/contactsController.js
> +
Пофіксив. Додав перевірку 
`if (updatedContact === null) {
      return res
        .status(404)
        .json({ message: `Contact id ${contactId} Not found` });
    }`

2023-01-13 20:50 UTC, AlexUKDev commented on controllers/contactsController.js
> +  }
Додав міделвари з валідацією. Потестив, наче все працює. Ще відрефакторив код (додав диструктуризації трохи).

2023-01-13 20:55 UTC, AlexUKDev commented on controllers/contactsController.js
> +    }
Відрефакторив код також.

2023-01-13 20:59 UTC, AlexUKDev commented on server.js
> +startServer();
<img width="455" alt="Screenshot 2023-01-13 at 22 56 15" src="https://user-images.githubusercontent.com/61418792/212417608-055f88ff-7f42-4774-8532-87583c85e410.png">

Зазвичай усі ментори казали дивитись на метрики пакету. Цей пакет  не підтримується (останні оновлення 2 роки тому), та 9 скачувань за тиждень (не зовсім популярний).  Як на мене немає сенсу навіть розбиратись що це за пакет та як він працює.

2023-01-14 06:41 UTC, KhYulian commented on db/connectionMongoDb.js
> +// const options = {};
// const options = {}; - яка потреба в цьому коментарі ?)

2023-01-14 06:43 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-14 06:43 UTC, KhYulian commented on middlewares/validationMiddleware.js
> +    });
винесіть const addContactSchema в окремий файл

2023-01-14 06:43 UTC, KhYulian commented on middlewares/validationMiddleware.js
> +    });
винесіть const updateContactSchemaв окремий файл

2023-01-14 06:43 UTC, KhYulian commented on middlewares/validationMiddleware.js
> +    });
теж винесіть

2023-01-14 07:15 UTC, AlexUKDev commented on middlewares/validationMiddleware.js
> +    });
1.) Rescheduled validation schemas in validation/validationJoiSchemas.js;
2.) Сode refactoring
3.) Renamed route file
4.)Tested on postman

2023-01-14 13:15 UTC, KhYulian approved these changes
Чудова робота :)

2023-01-14 13:15 UTC, merged